# mpv config

# fullscreen
fs

# use yt-dlp instead of youtube-dl
script-opts=ytdl_hook-ytdl_path=/usr/bin/yt-dlp

# gpu tweaks
profile=gpu-hq
gpu-api=vulkan

# monitor tweaks
target-prim=dci-p3 


# screenshot:
screenshot-format=png
screenshot-high-bit-depth=yes
screenshot-png-compression=3 

# deband filter (for anime)
deband=yes

# deband tweaks
deband-iterations=2 # 1-16.
deband-threshold=35 # 0-4096.
deband-range=20 # 1-64.
deband-grain=5 # 0-4096.

# dither depth
dither-depth=auto

# audio tweaks
volume=100
volume-max=100
